dev:
  sessions:
    default:
      identity_map_enabled: true
      database: autozone
      hosts:
        - 192.168.2.14:27017
local_dev:
  sessions:
    default:
      identity_map_enabled: true
      database: chezhongguo_development
      hosts:
        - 127.0.0.1:27017
chezhongguo:
  sessions:
    default:
      identity_map_enabled: true	
      database: chezhongguo
      hosts:
        - 127.0.0.1:27017
